apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-db-pv
  namespace: minishop
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/product-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cart-db-pv
  namespace: minishop
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/cart-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-db-pv
  namespace: minishop
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/order-db 